name: Run OpKey CLI

on:
  workflow_dispatch:

jobs:
  run-cli:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Java
        run: java -version
